version: '2'

services:
  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=orderer
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=orderer.block
      - ORDERER_GENERAL_LOCALMSPID=DEFAULT
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./msp:/etc/hyperledger/msp
      - ./orderer.block:/etc/hyperledger/fabric/orderer.block
    ports:
      - 7050:7050
  peer0:
    container_name: peer0
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_ADDRESS=peer5:7051
      - CORE_PEER_ADDRESS=peer6:7051
      - CORE_PEER_ADDRESS=peer7:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer

  peer1:
    container_name: peer1
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer1
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_ADDRESS=peer5:7051
      - CORE_PEER_ADDRESS=peer6:7051
      - CORE_PEER_ADDRESS=peer7:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7055:7051
      - 7056:7053
    depends_on:
      - orderer


  peer2:
    container_name: peer2
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer2
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_ADDRESS=peer5:7051
      - CORE_PEER_ADDRESS=peer6:7051
      - CORE_PEER_ADDRESS=peer7:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7057:7051
      - 7058:7053
    depends_on:
      - orderer

  peer3:
    container_name: peer3
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer3
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_ADDRESS=peer5:7051
      - CORE_PEER_ADDRESS=peer6:7051
      - CORE_PEER_ADDRESS=peer7:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7059:7051
      - 7060:7053
    depends_on:
      - orderer


  peer4:
    container_name: peer4
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer4
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_ADDRESS=peer5:7051
      - CORE_PEER_ADDRESS=peer6:7051
      - CORE_PEER_ADDRESS=peer7:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7061:7051
      - 7062:7053
    depends_on:
      - orderer

  peer5:
    container_name: peer5
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer5
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_ADDRESS=peer5:7051
      - CORE_PEER_ADDRESS=peer6:7051
      - CORE_PEER_ADDRESS=peer7:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer5:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7063:7051
      - 7064:7053
    depends_on:
      - orderer

  peer6:
    container_name: peer6
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer6
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_ADDRESS=peer5:7051
      - CORE_PEER_ADDRESS=peer6:7051
      - CORE_PEER_ADDRESS=peer7:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer6:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7065:7051
      - 7066:7053
    depends_on:
      - orderer

  peer7:
    container_name: peer7
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer7
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_ADDRESS=peer5:7051
      - CORE_PEER_ADDRESS=peer6:7051
      - CORE_PEER_ADDRESS=peer7:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer7:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7067:7051
      - 7068:7053
    depends_on:
      - orderer

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_ADDRESS=peer5:7051
      - CORE_PEER_ADDRESS=peer6:7051
      - CORE_PEER_ADDRESS=peer7:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c './script.sh'
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
        - ./../chaincode:/opt/gopath/src/chaincodedev/chaincode
        - ./:/opt/gopath/src/chaincodedev/
    depends_on:
      - orderer
      - peer1
      - peer0
      - peer2
      - peer3
      - peer4
      - peer5
      - peer6
      - peer7

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=example02
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_ADDRESS=peer5:7051
      - CORE_PEER_ADDRESS=peer6:7051
      - CORE_PEER_ADDRESS=peer7:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
        - ./../chaincode:/opt/gopath/src/chaincode
    depends_on:
      - orderer
      - peer0
      - peer1
      - peer2
      - peer3
      - peer4
      - peer5
      - peer6
      - peer7
